name: Status Check

on:
  push:
    branches:
      - main

jobs:
  check-directory-changes:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Changed Directories
      id: get_changed_dirs
      run: |
        changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -o '^[^/]\+/' | sort -u)
        echo "::set-output name=changed_dirs::$changed_dirs"

    - name: Run Workflow for Changed Directories
      run: |
        changed_dirs="${{ steps.get_changed_dirs.outputs.changed_dirs }}"
        excluded_dirs=("testdocs/") 

        for dir in $changed_dirs; do
          # Check if the current directory is not in the excluded list
          if [[ ! " ${excluded_dirs[@]} " =~ " $dir " ]]; then
            echo "Running workflow for changed directory: $dir"

            # Customize this step to run your specific workflow logic
            # For example, replace this with your test commands
            echo "Running tests for directory: $dir"
            
          else
            echo "Directory $dir is excluded. Skipping..."
          fi
        done
